"""Change club scale to type

Revision ID: e2dfc9f43362
Revises: 3b054ab2c235
Create Date: 2025-03-22 18:07:17.483445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2dfc9f43362'
down_revision = '3b054ab2c235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=64), nullable=True))
        batch_op.drop_column('scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
